name: Self Driving Checks

on:
  push:
    branches: [ master, pylint ]
  pull_request:
    branches: [ master, pylint ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code checks
      run: |
        git update-index --chmod=+x scripts/code_formatter.sh
        sudgit update-index --chmod=+xo scripts/import_formatter.sh
        git update-index --chmod=+x scripts/pylint.sh

