name: Flight Software HOOTL Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'standalone/**'
      - 'tools/**'
      - 'README.md'
      - 'LICENSE'
      - 'ptest/README.md'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Autopass CI Testing Script
      run: |
        python tools/testing/auto_pass.py
        !(python tools/testing/auto_fail.py)