
   
name: all-lints

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          use-pylint: true
